---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(paqueteMET)
library(ggplot2)
library(paqueteMET) 
library(flexdashboard) 
library(devtools)
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Chart A

```{r}



  ```

### Chart B

```{r}


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}


```

### Chart D

```{r}
ggplot(CarreraLuz22, aes(x = CarreraLuz22$categoria)) +                      #1
  #geom_bar() +                                             #2
  geom_bar(width=0.5, colour="red", fill="skyblue") +       #2 
  
  labs(x="Sexo",y= "Frecuencia")  +              #3               
  ylim(c(0,3000)) +                               #4
  #xlim(c(0,300)) +                              #4
  ggtitle("Diagrama de barras")  +               #5
  
  # theme_bw() +                                 #6
  theme_bw(base_size = 12) +                     #6
  #coord_flip() +                                #7
  
  geom_text(aes(label=..count..), stat='count',  #8
            position=position_dodge(0.9), 
            vjust=-0.5, 
            size=5.0
            ) + 
  facet_wrap(~"Variable Sexo")    

```

